apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: aws-alb-ingress-controller
  app.kubernetes.io/instance: aws-alb-ingress-controller-v0.7.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: aws-alb-ingress-controller
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.7.0
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
